#dnf install mysql-server -y
#systemctl enable mysqld
#systemctl start mysqld
#mysql_secure_installation --set-root-pass ExpenseApp@1
#mysql_secure_installation --set-root-pass {{mysql_root_password}}

- name: configure db server
  hosts: db
  become: yes
  vars_files:
  - credentials.yaml
  roles:
  - db
  